name: Run Selenium Tests and Publish Allure Report

on:
  workflow_dispatch:       # Manual trigger
  schedule:
    - cron: "0 2 * * *"   # Daily at 2 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest with Allure (Headless Chrome)
      env:
        CI: true
      run: |
        pytest --env=production

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        destination_dir: allure-report
        publish_branch: gh-pages
